# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "root"

  # auth-service
  - package-ecosystem: "pip"
    directory: "/auth-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "auth-service"

  # item-service
  - package-ecosystem: "pip"
    directory: "/item-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "item-service"

  # matching-service
  - package-ecosystem: "pip"
    directory: "/matching-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "matching-service"

  # recovery-case-service
  - package-ecosystem: "pip"
    directory: "/recovery-case-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "recovery-case-service"

  # Gateway
  - package-ecosystem: "pip"
    directory: "/gateway"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "gateway"
